name: Check actions

on: workflow_call

jobs:
  check-actions:
    timeout-minutes: 30
    name: Check github actions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Check Changed Files
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            actions:
              - ".github/workflows/*.yml"
              - ".github/workflows/*.yaml"
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        if: steps.filter.outputs.actions == 'true'
        with:
          aqua_version: v2.62.1
      - name: Linting
        if: steps.filter.outputs.actions == 'true'
        run: |
          ghalint run
          actionlint
